[project]
name = "sqlite"
version = "0.1.0"
description = "EMS SQLite version"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "tabulate>=0.9.0",
]
